### ISSUE TITLE
[Initial Work] Setup Folder Structure

### ISSUE THREAD

**Issue by mkaulfers** [lightPlugins/Vaulty#4]
Acceptance Criteria
- As a developer I want a solid package structure so that I can keep my code organized and tidy. 

Goals
- Add packages in the main package for the following things. Each sub-package should contain nothing for this work to be considered "Done".
- interfaces
- models
- managers
- utilities
- enums
- commands

![image](https://github.com/lightPlugins/Vaulty/assets/42121989/d06bf2b8-00fe-4314-93fa-4ec8fcead778)

**Comment by lightPlugins** [comment]
not needed for Vaulty
